### ISSUE TITLE
What about the PR-Tab?

### ISSUE THREAD

**Issue by Suven** [zachlysobey/github-hacktoberfest#1]
Although it's not an API-Endpoint, you might just consider using this URL

https://github.com/pulls?q=is%3Apr+author%3ASuven

**Comment by zachlysobey** [comment]
Wow, almost forgot about this project. Suprised you stumbled across it.

So, it looks like we _could_ scrape the contents of this page and get a PR count, but the goal of this project was to count commits.

**Comment by Suven** [comment]
Ah okay. Then this years hacktoberfest rules may have changed.

**Comment by zachlysobey** [comment]
Yup, it checks out:
- _2014_: https://www.digitalocean.com/company/blog/hacktoberfest/
- _2014_: https://github.com/blog/2067-hacktoberfest-contribute-to-open-source-in-october

Thanks for posting here though, totally reminded me to sign up for that promotion. That T-Shirt will be mine this year!

**Comment by zachlysobey** [comment]
I just opened a new issue where we can discuss whether to resuscitate this project:
https://github.com/zachlysobey/github-hacktoberfest/issues/2
