### ISSUE TITLE
Should we resuscitate this project for the 2015 promotion?

### ISSUE THREAD

**Issue by zachlysobey** [zachlysobey/github-hacktoberfest#2]
[The new 2015  promotion](https://github.com/blog/2067-hacktoberfest-contribute-to-open-source-in-october) requires that you sign up at digital ocean, and make 4 Pull requests to Open Source projects on GitHub in the month of October.

Big thanks to @Suven for opening [an issue](https://github.com/zachlysobey/github-hacktoberfest/issues/1) suggesting an approach to getting a PR count. In doing so, he reminded me about this project and promotion.

What do you think @KrishnaRSampath @mconklin @AmundsenJunior @Suven? 

**Let's get some T-Shirts this year!**

Seems to me that there may be a really easy way of doing this -- maybe a single API call? [@Suven posted a page](https://github.com/zachlysobey/github-hacktoberfest/issues/1) that we'd be able to scrape potentially, but there is probably an easier way.

**Comment by KrishnaRSampath** [comment]
I'm totally in!

**Comment by zachlysobey** [comment]
Well... I'm out ;-)
http://hf.heidilabs.com/#
