### ISSUE TITLE
Count PR's through the public API?

### ISSUE THREAD

**Issue by zachlysobey** [zachlysobey/github-hacktoberfest#3]
I think we can do this.

[From their FAQ](https://hacktoberfest.digitalocean.com/):

> How will you know how many PRs I have submitted?
> 
> Answer: We’ve created a simple GitHub API script that tells us!

If they did it, we should be able to (heck maybe they open sourced it, and we don't even need to).

Maybe the [events API](https://developer.github.com/v3/activity/events/) [PullRequest event](https://developer.github.com/v3/activity/events/types/#pullrequestevent) is what we want?

**Comment by zachlysobey** [comment]
They did it. We don't need to.
http://hf.heidilabs.com/#

**Comment by AmundsenJunior** [comment]
Fork it, add a feature, make a pull request. Get that t-shirt!

**Comment by zachlysobey** [comment]
hahah yup. I've already hit the number, so that shirt is mine this year!

**Comment by 5chdn** [comment]
hello 2016.

![murmeltier_derlandschaftszoo_murmeltier_gellermichael_2016-04-25_03-59-43_14936](https://cloud.githubusercontent.com/assets/15729797/19087980/706c1036-8a74-11e6-93ae-6c50c2b7f936.jpg)

the links above are going nowhere. does anyone remember the related github repositories?

**Comment by 5chdn** [comment]
Nevermind, got it: https://github.com/erikaheidi/hacktoberfest-verify/issues/9
